product_number: 3
resource_number: 2
resource_matrix:
  - [1, 0]
  - [0, 1]
  - [1, 1]
price_set_matrix:
  - [5, 10, 15, 100000000]
  - [5, 15, 10000000]
  - [10, 20, 100000000]
horizon: 20
budget: [10, 8]
scaling_list: [1, 20, 100, 1000]
demand_model: "MNL"

MNL:
  d: [10.0, 8, 12]   # 产品吸引力向量，长度为product_number
  mu: 10.0           # 理性参数，正数
  u0: 0              # 不购买的效用，默认0
  gamma: 1.0         # 价格敏感度，正数

Linear:
  psi: [10, 8, 6]    # 截距向量，长度为product_number
  theta:
    - [-0.5, -0.1, -0.1]
    - [-0.1, -0.5, -0.1]
    - [-0.1, -0.1, -0.5]

# 代表每个产品对自身价格敏感，对其他产品价格也有影响
tolerance: 1e-4
